### ISSUE TITLE
TreeDict issues

### ISSUE THREAD

**Issue by sjonesstmn** [samvv/scl.js#10]
Hi, I tried to use your library and I encountered a couple of issues with TreeDict:

1. I tried using a Scl.TreeDict<VectorType, Value> and it did not work compared to when I did Scl.TreeDirect<VectorType, Value>
2. I found that it's not possible to override the compareKeys value using TreeDict. The code does not pass the compareKeys value to the base classes. E.g. compareKeys below does not propagate via the `opts` to `BST.isKeyLessThan`:
```
Scl.TreeDict<VectorType, Value>({
       compareKeys: (a, b): boolean => {
         // left side less than right side
         return customVectorCompareVector(a, b) === -1;
       },
});
```

---

Thanks.

**Comment by samvv** [comment]
Hi, sorry for the very late reply, and thanks for filing an issue.

> I tried using a Scl.TreeDict<VectorType, Value> and it did not work compared to when I did Scl.TreeDirect<VectorType, Value>

Could you be more specific? What did not work? What was the error message? There is no `TreeDirect` type in `scl.js` IIRC.
