### ISSUE TITLE
Terminology 'Containers' vs 'collection classes'

### ISSUE THREAD

**Issue by BurtHarris** [samvv/scl.js#8]
The README.md in this repo talks about being a curated collection of ***containers***, but I would suggest ***collection classes*** might be more standard terminology for classes like Bag, Set, List, etc.   

In my experience, the term 'container' has developed a different meaning in many software engineering contexts.   This other meaning is well documented in [Inversion of Control Containers and the Dependency Injection pattern](https://www.martinfowler.com/articles/injection.html) by Martin Fowler.   An IoC container has a very different purpose than a collection.

**Comment by samvv** [comment]
Very good point! I borrowed the name from C++, where I had a bit more experience in when I started this project. I'll look into changing the name when I have the time.
